### ISSUE TITLE
Discuss with the community how to run a governance model

### ISSUE THREAD

**Issue by bencer** [falcosecurity/cloud-native-security-hub#13]
Define an open model for project governance so there is a policy on what gets accepted into the hub and what requirements are put in place

**Comment by KnoxAnderson** [comment]
The security hub should be more of an open option where rules for auditing, detection use cases, or even rules that could be used for troubleshooting could be shared. 

The place where we'll need to be stricter is in the default ruleset that ships with falco. There could be some process where a rule gets added to the hub first and then goes through some type of promotion process before making it into the default set.
